import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

import {
  GoAccordionModule,
  GoActionSheetModule,
  GoBadgeModule,
  GoButtonModule,
  GoCardModule,
  GoCheckboxModule,
  GoCopyModule,
  GoDatepickerModule,
  GoEditorModule,
  GoFileUploadModule,
  GoFooterModule,
  GoHeaderBarModule,
  GoHeaderModule,
  GoIconButtonModule,
  GoIconModule,
  GoInputModule,
  GoLayoutModule,
  GoLoaderModule,
  GoModalModule,
  GoOffCanvasModule,
  GoPillModule,
  GoPortalModule,
  GoProgressBarModule,
  GoRadioModule,
  GoSearchModule,
  GoSelectModule,
  GoSideNavModule,
  GoSwitchToggleModule,
  GoTableModule,
  GoTextAreaModule,
  GoTimepickerModule,
  GoToasterModule,
  GoToastModule,
} from '../../../go-lib/src/public_api';

const GO_LIB_MODULES = [
  GoAccordionModule,
  GoActionSheetModule,
  GoBadgeModule,
  GoButtonModule,
  GoCardModule,
  GoCheckboxModule,
  GoCopyModule,
  GoDatepickerModule,
  GoEditorModule,
  GoFileUploadModule,
  GoFooterModule,
  GoHeaderBarModule,
  GoHeaderModule,
  GoIconButtonModule,
  GoIconModule,
  GoInputModule,
  GoLayoutModule,
  GoLoaderModule,
  GoModalModule,
  GoOffCanvasModule,
  GoPillModule,
  GoPortalModule,
  GoProgressBarModule,
  GoRadioModule,
  GoSearchModule,
  GoSelectModule,
  GoSideNavModule,
  GoSwitchToggleModule,
  GoTableModule,
  GoTextAreaModule,
  GoTimepickerModule,
  GoToasterModule,
  GoToastModule,
];

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    RouterModule,
    ...GO_LIB_MODULES,
  ],
  exports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    RouterModule,
    ...GO_LIB_MODULES,
  ],
})
export class TesterImportsModule {}
