import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { Highlight } from 'ngx-highlightjs';

import {
  GoAccordionModule,
  GoActionSheetModule,
  GoBadgeModule,
  GoBadgePillModule,
  GoButtonModule,
  GoCardModule,
  GoCheckboxModule,
  GoCopyModule,
  GoDatepickerModule,
  GoEditorModule,
  GoFileUploadModule,
  GoFooterModule,
  GoHeaderBarModule,
  GoHeaderModule,
  GoIconButtonModule,
  GoIconModule,
  GoInputModule,
  GoLayoutModule,
  GoLoaderModule,
  GoModalModule,
  GoOffCanvasModule,
  GoPillModule,
  GoProgressBarModule,
  GoRadioModule,
  GoSearchModule,
  GoSelectModule,
  GoSharedModule,
  GoSideNavModule,
  GoSwitchToggleModule,
  GoTableModule,
  GoTabModule,
  GoTextAreaModule,
  GoTimepickerModule,
  GoToasterModule,
  GoToastModule,
  GoTreeModule
} from 'projects/go-lib/src/public_api';

import { SharedModule } from './shared.module';

const GO_LIB_MODULES = [
  GoAccordionModule,
  GoActionSheetModule,
  GoBadgeModule,
  GoBadgePillModule,
  GoButtonModule,
  GoCardModule,
  GoCheckboxModule,
  GoCopyModule,
  GoDatepickerModule,
  GoEditorModule,
  GoFileUploadModule,
  GoFooterModule,
  GoHeaderBarModule,
  GoHeaderModule,
  GoIconButtonModule,
  GoIconModule,
  GoInputModule,
  GoLayoutModule,
  GoLoaderModule,
  GoModalModule,
  GoOffCanvasModule,
  GoPillModule,
  GoProgressBarModule,
  GoRadioModule,
  GoSearchModule,
  GoSelectModule,
  GoSharedModule,
  GoSideNavModule,
  GoSwitchToggleModule,
  GoTableModule,
  GoTabModule,
  GoTextAreaModule,
  GoTimepickerModule,
  GoToasterModule,
  GoToastModule,
  GoTreeModule,
];

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    RouterModule,
    Highlight,
    SharedModule,
    ...GO_LIB_MODULES,
  ],
  exports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    RouterModule,
    Highlight,
    SharedModule,
    ...GO_LIB_MODULES,
  ],
})
export class DemoImportsModule {}
