name: CD

on:
  push:
    branches:
      - main
      - PCP-1226-publish-to-nexus-1.17.0

jobs:
  createRelease:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: projects/go-lib

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          tag_name: v${{ steps.package-version.outputs.current-version }}
          target_commitish: main

  publishPackage:
    name: Publish New Package
    runs-on: [self-hosted, oracle9, gomobilesharedstagedeploy]
    needs: createRelease
    env:
      NPM_TOKEN: ${{ secrets.NPM_PWD }}
      NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NVMRC }}

      - name: Install npm Packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Disable strict SSL for Nexus
        run: npm config set strict-ssl false

      - name: Create .npmrc for Nexus publish
        run: |
          cat > .npmrc << EOF
          always-auth=true
          registry=https://dc2nexus.corp.tangoe.com:8443/nexus/content/repositories/tangoenpm-hosted/
          //dc2nexus.corp.tangoe.com:8443/nexus/content/repositories/tangoenpm-hosted/:_auth=${{ secrets.NPM_PWD }}
          email=${{ secrets.NPM_EMAIL }}
          EOF
          cp .npmrc projects/go-lib/.npmrc

      - name: Publish Package
        run: npm run publish -- --ignore-scripts