name: CD

on:
  push:
    branches:
      - main

jobs:
  createRelease:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: projects/go-lib

      - name: Log Package Version
        run: echo "📦 Publishing version - ${{ steps.package-version.outputs.current-version }}"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          tag_name: v${{ steps.package-version.outputs.current-version }}
          target_commitish: main

  publishPackage:
    name: Publish New Package
    runs-on: [self-hosted, autoscaling, oracle9, ruby3.0.6, gomobilesharedstagedeploy]
    needs: createRelease
    env:
      NPM_TOKEN: ${{ secrets.NPM_PWD }}
      NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v5
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

      - name: Install Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ env.NVMRC }}

      - name: Install npm Packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Create .npmrc for Nexus publish
        run: |
          cat > .npmrc << EOF
          always-auth=true
          registry=https://dc2nexus.corp.tangoe.com:8443/nexus/content/repositories/tangoenpm-hosted/
          //dc2nexus.corp.tangoe.com:8443/nexus/content/repositories/tangoenpm-hosted/:_auth=${{ secrets.NPM_PWD }}
          email=${{ secrets.NPM_EMAIL }}
          EOF
          cp .npmrc projects/go-lib/.npmrc

      - name: Publish Package
        run: npm run publish -- --ignore-scripts
        env:
          NODE_EXTRA_CA_CERTS: ${{ github.workspace }}/certs/TangoeCA.crt