name: CI

on: [pull_request]

concurrency:
  group: ci_${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  library:
    name: Library Build & Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: library-npm-${{ hashFiles('package-lock.json') }}
      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NVMRC }}
      - name: Install npm Packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run Production Build
        run: npm run build_lib
      - name: Run Tests
        run: npm run test_lib:ci
